version: '2'
services:
    silkworkbench:
        image: openbudgets/silkworkbench
        build: ./silkworkbench
        volumes:
            - ../volumes/silkworkbench/silk:/root/.silk
        ports:
            - "9000:9000"
    alignmentmysql:
        image: openbudgets/alignmentmysql
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        env_file:
            - ../env.example
        ports:
            - "3306:3307"
    alignmentredis:
        image: openbudgets/alignmentredis
        build: ./alignmentredis
        volumes:
            - ../volumes/alignment/redis:/data
    alignmentui:
        image: openbudgets/alignmentui
        build: ./alignmentui
        volumes:
            - ../volumes/virtuosoStaging/data:/data
        env_file:
            - ../env.example
        links:
            - alignmentmysql
            - alignmentredis
    linkedpipes_fdp:
        image: openbudgets/linkedpipes
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    sshserver:
        image: openbudgets/sshserver
        build: ./sshserver
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        image: openbudgets/virtuoso
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/virtuosoStaging/upload:/upload
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/cronjobs/importFromTrig:/etc/cron.hourly/importFromTrig
            - ./virtuoso/cronjobs/importFromTTL:/etc/cron.hourly/importFromTTL
        env_file:
            - ../env.example
        environment:
            - SPARQL_UPDATE=true
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        image: openbudgets/virtuoso
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
        env_file:
            - ../env.example
        environment:
            - SPARQL_UPDATE=false
        ports:
            - "8891:8890"
            - "1112:1111"
    virtuoso_staging_old:
        image: openbudgets/virtuoso
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoStagingOld/data:/data
            - ../volumes/virtuosoStagingOld/upload:/upload
            - ../volumes/nginx/dumps:/dumps
        env_file:
            - ../env.example
        environment:
            - SPARQL_UPDATE=true
        ports:
            - "8893:8890"
            - "1113:1111"
    triple_store_staging:
        image: openbudgets/triple_store_staging
        build: ./fuseki
        volumes:
            - ./fuseki/staging/start.sh:/start.sh
            - ./fuseki/staging:/staging
            - ../volumes/tripleStoreStaging/log:/var/log
            - ../volumes/tripleStoreStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
        ports:
            - "33030:3030"
            - "39001:9001" # supervisord frontend
    triple_store_production:
        image: openbudgets/triple_store_production
        build: ./fuseki
        volumes:
            - ./fuseki/production/start.sh:/start.sh
            - ../volumes/tripleStoreProduction/log:/var/log
            - ../volumes/tripleStoreProduction/data:/data
            - ../volumes/tripleStoreStaging/data:/newdata
        ports:
            - "43030:3030"
            - "49001:9001" # supervisord frontend
    rudolf:
        image: openbudgets/rudolf
        build: ./rudolf
        volumes:
            - ../volumes/rudolf/www:/var/www
        links:
            - triple_store_production
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        image: openbudgets/rdfbrowser
        build: ./rdfbrowser
        volumes:
            - ../volumes/rdfbrowser/storage/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ./rdfbrowser/dev/apache2.conf:/etc/apache2/apache2.conf
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dampostgres:
        image: openbudgets/dampostgres
        build: ./dampostgres
        volumes:
            - ../volumes/dam/dampostgres:/var/lib/postgresql/data
        env_file:
            - ../env.example
    damapp:
        image: openbudgets/damapp
        build: ./damapp
        ports:
            - "5000:5000"
        links:
            - dampostgres
        env_file:
            - ../env.example
    nginx:
        image: openbudgets/nginx
        build: ./nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx_dev.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/static_files/images:/var/www/images
            - ./nginx/static_files/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - triple_store_staging
            - triple_store_production
            - virtuoso_staging
            - virtuoso_production
            - virtuoso_staging_old
            - rudolf
            - os-viewer
            - os-explorer
            - os-admin
            - indigo
            - rdfbrowser
            - alignmentui
            - microsite
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:   #image: openspending/os-viewer
        image: openbudgets/os-viewer
        build: ./os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/dev_config:/app/app/config
            - ./volumes/os-viewer/os_viewer_themes:/app/app/config/themes
        environment:
            - DEFAULT_HOST=http://localhost
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://localhost
            - OS_VIEWER_API_HOST=http://localhost
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://localhost
            - OS_VIEWER_DATAMINE_HOST=http://localhost
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-explorer:
        image: openbudgets/os-explorer
        build: ./os-explorer
        volumes:
          - ./os-explorer/dev_themes:/app/app/scripts/services/themes
        expose:
          - "8000"
        environment:
          - WORKDIR=/apps
    os-admin:
        image: openbudgets/os-admin
        expose:
          - "8000"
        restart: always
    indigo:
        image: openbudgets/indigo
        build: ./indigo
        ports:
          - "4200:4200"
        links:
          - damapp
    microsite:
        build: ./microsite
        restart: always
        volumes:
          - ./volumes/os_viewer/os_viewer_themes:/usr/src/app
        expose:
          - "8000"
        depends_on:
          - os-viewer
        links:
          - os-viewer
        environment:
          # non secret static environment variables
          - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
          - OS_VIEWER_HOST=os-viewer
          - OS_API=http://next.openspending.org/api/3

#    vocol:
#        build: ./vocol
#        ports:
#          - "4200:4200"






# Subnet-Size net-Mask-Size (CIDR)
# 256 24
# 128 25
# 64 26
# 32 27
# 16 28 <<<<<
# 8 29
# 4 30
# 2 31
# 1 32

    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







