version: '2'
services:
    microsite:
        image: openbudgets/microsite
        build: ./microsite
        volumes:
            - ../volumes/osviewer/themes:/microsite/os_viewer_themes
            - ../volumes/microsite/data/db.sqlite3:/microsite/db.sqlite3
        ports:
            - "8003:8000"
        links:
            - os-viewer
        environment:
            - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
            - OS_VIEWER_HOST=http://apps.openbudgets.eu/viewer
            - OS_API=http://apps.openbudgets.eu/api/3
        env_file:
            - ../.env
    obeu_microsite:
        image: openbudgets/microsite
        build: ./obeu-microsite
        volumes:
            - ../volumes/osviewer/themes:/microsite/os_viewer_themes
            - ../volumes/microsite/data/db.sqlite3:/microsite/db.sqlite3
        ports:
            - "8009:8000"
        links:
            - os-viewer
        environment:
            - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
            - OS_VIEWER_HOST=http://apps.openbudgets.eu/viewer
            - OS_API=http://apps.openbudgets.eu/api/3
        env_file:
            - ../.env
    silkworkbench:
        image: openbudgets/silkworkbench
        build: ./silkworkbench
        volumes:
            - ../volumes/silkworkbench/silk:/root/.silk
        ports:
            - "9000:9000"
    alignmentmysql:
        image: openbudgets/alignmentmysql
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        env_file:
            - ../.env
        ports:
            - "3306:3307"
    alignment:
        image: openbudgets/alignment
        build: ./alignment
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/alignment/composer:/root/.composer/cache
            - ../volumes/alignment/storage/app/projects:/var/www/alignment/storage/app/projects
            - ../volumes/alignment/storage/app/public/json_serializer:/var/www/alignment/storage/app/public/json_serializer
            - ../volumes/alignment/storage/logs:/var/www/alignment/storage/logs
            - ../volumes/alignment/stappler:/var/www/alignment/public/system
        env_file:
            - ../.env
        expose:
          - "80"
        ports:
            - "9559:80"
        links:
            - alignmentmysql
    linkedpipes_fdp:
        image: openbudgets/linkedpipes
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
            - ./linkedpipes/configuration_update.properties:/etl/deploy/configuration.properties
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - virtuoso_staging
            - sshserver
    linkedpipes_1:
        image: openbudgets/linkedpipes
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_1/data:/data
            - ../volumes/linkedpipes_1/log:/var/log
            - ./linkedpipes/configuration_update_1.properties:/etl/deploy/configuration.properties
        ports:
            - "8282:8282" # Webserver & URI dereferencable URI for pipelines + templates
            - "8270:8270" # executor-monitor.webserver.port
            - "8221:8221" # executor-monitor.ftp.port
            - "8223-8230:8223-8230" # Linked Pipes FTP data port
            - "8201:9201" # supervisord frontend
        links:
            - virtuoso_staging
            - sshserver
    sshserver:
        image: openbudgets/sshserver
        build: ./sshserver
        restart: always
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        image: openbudgets/virtuoso
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/virtuosoStaging/upload:/upload
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/staging/virtuoso.ini:/virtuoso.ini
        env_file:
            - ../.env
        environment:
            - SPARQL_UPDATE=true
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        image: openbudgets/virtuoso
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
            - ./virtuoso/production/virtuoso.ini:/virtuoso.ini
        env_file:
            - ../.env
        environment:
            - SPARQL_UPDATE=false
        ports:
            - "8891:8890"
            - "1112:1111"
    virtuoso_staging_old:
        image: openbudgets/virtuoso
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoStagingOld/data:/data
            - ../volumes/virtuosoStagingOld/upload:/upload
            - ../volumes/nginx/dumps:/dumps
        env_file:
            - ../.env
        environment:
            - SPARQL_UPDATE=true
        ports:
            - "8893:8890"
            - "1113:1111"
    rudolf:
        image: openbudgets/rudolf
        build: ./rudolf
        restart: always
        volumes:
            - ../volumes/rudolf/www/log/refreshCache.log:/var/www/log/refreshCache.log
        links:
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        image: openbudgets/rdfbrowser
        build: ./rdfbrowser
        volumes:
            - ../volumes/rdfbrowser/storage/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ./rdfbrowser/dev/apache2.conf:/etc/apache2/apache2.conf
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dampostgres:
        image: openbudgets/dampostgres
        build: ./dampostgres
        volumes:
            - ../volumes/dam/dampostgres:/var/lib/postgresql/data
        env_file:
            - ../.env
    kpi:
        image: openbudgets/kpi
        build: ./kpi
        volumes:
            - ../volumes/kpi/database:/var/www/database
            #- ./kpi/dev/apache2.conf:/etc/apache2/apache2.conf
            - ../volumes/kpi/composer:/root/.composer
        ports:
            - "8112:80"
    damapp:
        image: openbudgets/damapp
        build: ./damapp
        #volumes:
        #    - ../volumes/dam/fonts:/usr/local/share/fonts/
        ports:
            - "5000:5000"
        links:
            - dampostgres
            - opencpu
        env_file:
            - ../.env
    outlierdm:
        image: openbudgets/outlierdm
        build: ./outlierdm
        ports:
            - "5555:5000"
    nginx:
        image: openbudgets/nginx
        build: ./nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/static_files/images:/var/www/images
            - ./nginx/static_files/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - virtuoso_staging
            - virtuoso_production
            - virtuoso_staging_old
            - rudolf
            - os-viewer
            - os-packager
            - indigo
            - rdfbrowser
            - alignment
            - microsite
            - obeu_microsite
            - damapp
            - opencpu
            - cors
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:   #image: openspending/os-viewer
        image: openbudgets/os-viewer
        build: ./os-viewer
        restart: always
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/prod_config:/config
            - ../volumes/osviewer/themes:/app/app/config/themes
        environment:
            - DEFAULT_HOST=http://apps.openbudgets.eu
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://apps.openbudgets.eu
            - OS_VIEWER_API_HOST=http://apps.openbudgets.eu
            - OS_VIEWER_AUTH_HOST=http://apps.openbudgets.eu
            - OS_VIEWER_SEARCH_HOST=http://apps.openbudgets.eu
            - OS_VIEWER_DATAMINE_HOST=http://apps.openbudgets.eu
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-packager:
        build: ./os-packager
        restart: always
        expose:
          - "8000"
        ports:
          - "9553:8000"
    indigo:
        image: openbudgets/indigo
        build: ./indigo
        ports:
          - "8442:80"
        links:
          - damapp
          - opencpu
    cors:
        build: ./cors
        restart: always
        expose:
          - "8080"
        ports:
          - "19102:8080"
    opencpu:
        image: openbudgets/opencpu
        build: ./opencpu
        ports:
          - "8666:80"
          - "8663:443"
          - "8004:8004"



