#!/usr/bin/env bash
# see: http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtBulkRDFLoader
# 1st argument: IMPORT_FOLDER within the container for example /dumps points to http://eis-openbudgets.iais.fraunhofer.de/dumps
# 2nd argument: DBA_PASSWORD
set -e

PATH=/apache-jena/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

clear_delete_file(){
    cd /upload
    : > ./delete_graphs_trig.tmp
    : > ./delete_graphs_trig.txt
}

populate_delete_file(){
    cd /upload
    find . -name "*.trig" | xargs -I"{}" riot "{}" | awk '{print $(NF-1)}' | uniq >> ./delete_graphs_trig.tmp
    # Remove empty lines:
    grep '[^[:blank:]]' < ./delete_graphs_trig.tmp > ./delete_graphs_trig.txt
}

clear_isql_file(){
    cd /upload
    : > tmp_trig.isql
}

populate_isql_file_with_deletes(){
    cd /upload
    echo "log_enable(3,1);" >> tmp_trig.isql
    while read -r LINE; do
        echo "SPARQL CLEAR GRAPH $LINE;" >> tmp_trig.isql
    done < ./delete_graphs_trig.txt
}

populate_isql_file_with_imports(){
    cd /upload
    . /setEnv
    echo "Importing started from /upload"
    echo "DELETE FROM DB.DBA.load_list;" >> tmp_trig.isql
    echo "ld_dir_all('/upload', '*.trig','not_used');" >> tmp_trig.isql
    echo "select * from DB.DBA.load_list;" >> tmp_trig.isql
    echo "rdf_loader_run();" >> tmp_trig.isql
    echo "rdf_loader_run();" >> tmp_trig.isql
    echo "rdf_loader_run();" >> tmp_trig.isql
    echo "rdf_loader_run();" >> tmp_trig.isql
}

execute_isql(){
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" tmp_trig.isql
}

clear_upload_dir(){
    cd /upload && find . -name "*.trig" | xargs -I"{}" rm "{}"
}

clear_delete_file
clear_isql_file

# Delete Graphs:
populate_delete_file
populate_isql_file_with_deletes

# Import Datasets:
populate_isql_file_with_imports

execute_isql
clear_upload_dir