#!/usr/bin/env bash
set -e

PATH=/apache-jena/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#### Helper functions #####

_find_graphs_to_delete(){
    echo "_find_graphs_to_delete"
    cd /upload
    # Clear temp files:
    : > ./delete_graphs.tmp
    : > ./delete_graphs.txt
    # Extract graphnames to update:
    find . -name "*.ttl.graph" | while read filename; do (cat "$filename";echo) >> ./delete_graphs.tmp; done
}

_create_delete_isql(){
    echo "_create_delete_isql"
    cd /upload
    # Clear temp file:
    : > ./delete_graphs.isql
    echo "log_enable(3,1);" >> delete_graphs.isql
    while read -r LINE; do
        echo "SPARQL CLEAR GRAPH <$LINE>;" >> delete_graphs.isql
    done < ./delete_graphs.txt
}

_create_import_isql(){
    echo "_create_import_isql"
    cd /upload
    # Clear temp file:
    : > ./import_datasets.isql
    echo "ld_dir_all('/upload', '*.ttl', NULL);" >> import_datasets.isql
    echo "select * from DB.DBA.load_list;" >> import_datasets.isql
}

#### main functions #####

delete_graphs(){
    echo "delete_graphs"
    _find_graphs_to_delete
    _create_delete_isql

    cd /upload
    . /setEnv
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" delete_graphs.isql
}

begin_bulk_upload(){
    echo "begin_bulk_upload"
    cd /upload
    . /setEnv
    # clean previous bulk upload schedule:
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DELETE FROM DB.DBA.load_list;"
    # disable indexing
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.VT_BATCH_UPDATE ('DB.DBA.RDF_OBJ', 'ON', NULL);"
}

run_bulk_upload(){
    echo "run_bulk_upload"
    _create_import_isql
    cd /upload
    . /setEnv
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="set isolation='uncommitted';"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" import_datasets.isql
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="rdf_loader_run();"
}

end_bulk_upload(){
    echo "end_bulk_upload"
    . /setEnv
    # enable indexing
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.RDF_OBJ_FT_RULE_ADD (null, null, 'All');"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.VT_INC_INDEX_DB_DBA_RDF_OBJ ();"
}

create_checkpoint(){
    echo "create_checkpoint"
    . /setEnv
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="commit WORK;"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="checkpoint;"
}

clear_upload_dir(){
    echo "clear_upload_dir"
    cd /upload && find . -name "*.ttl" | xargs -I"{}" rm "{}"
    cd /upload && find . -name "*.ttl.graph" | xargs -I"{}" rm "{}"
}

shut_down_virtuoso(){
    echo "shut_down_virtuoso"
    . /setEnv
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="shutdown();"
}

# Remove graphs for updates:
delete_graphs

# Import Datasets:
begin_bulk_upload
run_bulk_upload
end_bulk_upload

# Checkpoint for restart:
create_checkpoint

# Delete ttl-files:
clear_upload_dir

# Shutdown Virtuoso:
shut_down_virtuoso




