#!/usr/bin/env bash
set -e

PATH=/apache-jena/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#### Helper functions #####

_clear_tmp_files(){
    echo "_clear_tmp_files"
    cd /upload
    : > ./delete_graphs_trig.tmp
    : > ./delete_graphs_trig.txt
    : > tmp_trig.isql
}

_find_graphs_to_delete(){
    echo "_find_graphs_to_delete"
    cd /upload
    find . -name "*.trig" | xargs -I"{}" riot "{}" | awk '{print $(NF-1)}' | uniq >> ./delete_graphs_trig.tmp
    # Remove empty lines:
    grep '[^[:blank:]]' < ./delete_graphs_trig.tmp > ./delete_graphs_trig.txt
}

_create_sparql_deletes_isql(){
    echo "_create_sparql_deletes_isql"
    cd /uploads
    echo "log_enable(3,1);" >> tmp_trig.isql
    while read -r LINE; do
        echo "SPARQL CLEAR GRAPH $LINE;" >> tmp_trig.isql
    done < ./delete_graphs_trig.txt
}

_create_import_isql(){
    echo "_create_import_isql"
    cd /upload
    echo "Importing started from /upload"
    echo "ld_dir_all('/upload', '*.trig','not_used');" >> tmp_trig.isql
    echo "select * from DB.DBA.load_list;" >> tmp_trig.isql
}

_create_isql_file(){
    echo "_create_isql_file"
    _clear_tmp_files
    _find_graphs_to_delete
    _create_sparql_deletes_isql
    _create_import_isql
}

#### main functions #####

begin_bulk_upload(){
    echo "begin_bulk_upload"
    _create_isql_file
    . /setEnv
    # clean previous bulk upload schedule:
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DELETE FROM DB.DBA.load_list;"
    # disable indexing
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.VT_BATCH_UPDATE ('DB.DBA.RDF_OBJ', 'ON', NULL);"
}

run_bulk_upload(){
    echo "run_bulk_upload"
    . /setEnv
    cd /upload
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" tmp_trig.isql
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="set isolation='uncommitted';"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="rdf_loader_run();"
}

create_checkpoint(){
    echo "create_checkpoint"
    . /setEnv
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="checkpoint;"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="commit WORK;"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="checkpoint;"
}

end_bulk_upload(){
    echo "end_bulk_upload"
    . /setEnv
    # enable indexing
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.RDF_OBJ_FT_RULE_ADD (null, null, 'All');"
    /usr/local/virtuoso-opensource/bin/isql-v 1111 dba "$DBA_PASSWORD" exec="DB.DBA.VT_INC_INDEX_DB_DBA_RDF_OBJ ();"
}

clear_upload_dir(){
    echo "clear_upload_dir"
    cd /upload && find . -name "*.trig" | xargs -I"{}" rm "{}"
}

# Import Datasets:
begin_bulk_upload
run_bulk_upload
create_checkpoint
end_bulk_upload

# Delete trig-files:
clear_upload_dir


