#!/bin/sh

# Sync Folders Staging -> Production:
rm -rf /data/*
cp -r /newdata/* /data/.

# logging:
echo $(date +"%Y-%m-%d_%H-%M-%S Start Syncing TripleStores...")

# Restart Fuseki:
supervisorctl stop executor
kill -9 $(ps -ef | grep fuseki | grep -v grep | awk '{print $1}')
find . -name *.lock | xargs -i rm {}
supervisorctl start executor

# logging:
echo $(date +"%Y-%m-%d_%H-%M-%S Finished Syncing TripleStores...")