#!/usr/bin/env bash

echo "Renews the certificate if expiration is close. The certificate needs to be installed previously."

BASEDIR=$(dirname "$0")
echo "$BASEDIR"
docker build -t letsencrypt_img "$BASEDIR"

docker run --rm --name letsencrypt \
    -p 1086:80 \
    -v "$PWD/../volumes/nginx/letsencrypt/etc:/etc/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/www:/var/www" \
    letsencrypt_img \
    renew
