#!/usr/bin/env bash

echo "If run for the first time, please disable https 443 in nginx.conf."
echo "If the script has successfully run, enable https 443 in nginx.conf again."

# For subdomain: eis-openbudgets
mkdir -p ../volumes/nginx/letsencrypt/eis-openbudgets/www
mkdir -p ../volumes/nginx/letsencrypt/eis-openbudgets/lib
mkdir -p ../volumes/nginx/letsencrypt/eis-openbudgets/etc

# For subdomain: microsite-obeu
mkdir -p ../volumes/nginx/letsencrypt/microsite-obeu/www
mkdir -p ../volumes/nginx/letsencrypt/microsite-obeu/lib
mkdir -p ../volumes/nginx/letsencrypt/microsite-obeu/etc

docker build -t letsencrypt_img .

# For subdomain: eis-openbudgets
docker run --rm --name letsencrypt \
    -p 1086:80 \
    -v "$PWD/../volumes/nginx/letsencrypt/eis-openbudgets/etc:/etc/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/eis-openbudgets/lib:/var/lib/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/eis-openbudgets/www:/var/www" \
    letsencrypt_img \
    certonly \
    --authenticator webroot \
    --webroot \
    --webroot-path /var/www \
    --agree-tos \
    --renew-by-default \
    -d eis-openbudgets.iais.fraunhofer.de \
    -m maiklukasch@gmail.com \
    --server https://acme-staging.api.letsencrypt.org/directory \
    --debug \
    --standalone-supported-challenges http-01 \
    --verbose

# For subdomain: microsite-obeu
docker run --rm --name letsencrypt \
    -p 1086:80 \
    -v "$PWD/../volumes/nginx/letsencrypt/microsite-obeu/etc:/etc/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/microsite-obeu/lib:/var/lib/letsencrypt" \
    -v "$PWD/../volumes/nginx/letsencrypt/microsite-obeu/www:/var/www" \
    letsencrypt_img \
    certonly \
    --authenticator webroot \
    --webroot \
    --webroot-path /var/www \
    --agree-tos \
    --renew-by-default \
    -d microsite-obeu.iais.fraunhofer.de \
    -m maiklukasch@gmail.com \
    --server https://acme-staging.api.letsencrypt.org/directory \
    --debug \
    --standalone-supported-challenges http-01 \
    --verbose
#docker kill --signal=HUP dockerconfig_nginx_1
